runtime: python39  # or another version if you prefer
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  min_pending_latency: automatic
  max_pending_latency: automatic
entrypoint: python main.py
